# Generated by Django 3.2.9 on 2021-11-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('values', models.CharField(blank=True, max_length=45, null=True)),
                ('allowed_values', models.CharField(max_length=45)),
                ('modifiable', models.IntegerField()),
                ('source', models.CharField(max_length=45)),
                ('apply_type', models.CharField(max_length=45)),
                ('data_type', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'parameters',
                'managed': False,
            },
        ),
    ]
